### PR TITLE
Validate kubeconfig by keys; change regexp to cidr

### PR DESCRIPTION
**Pull request by ekhomyakova**
- add yaml validator for kubeconfig field of manual engine;
- remove regexp validator from network range of gce engine and
  replace it with cidr validator.

**DEPENDS ON** https://github.com/Mirantis/kqueen-ui/pull/69

### CODE REVIEW

**Comment by naumvd95** [comment]
@ekhomyakova flake8 failed

**Comment by atengler** [comment]
It seems this PR depends on - https://github.com/Mirantis/kqueen-ui/pull/69/ - in UI project, otherwise it seems OK

**Comment by naumvd95** [comment]
@ekhomyakova for future pls add depended commit link in commit body, for now, ill updated itty myself

**Comment by naumvd95** [comment]
do not merge due dependencies

**Pull request merged**
